apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mvc-deployment
spec:
  selector:
    matchLabels:
      app: mvc
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image: sushantjadhavhcl/mvc-asp-app:v1
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__ProductsContext
            value: Server=mssql-service;Database=ProductsContext;User=sa;Password=@Aa123456;
      
